"""Constants for per-session transcription report files."""

CONFIG_KEY_REPORTS = "reports"
CONFIG_KEY_REPORTS_DIR = "dir"
CONFIG_KEY_REPORTS_ENABLED = "enabled"

DEFAULT_REPORTS_DIR_NAME = "reports"
DEFAULT_REPORTS_ENABLED = True

REPORT_FILENAME_PREFIX = "session_"
REPORT_FILENAME_SUFFIX = ".txt"
REPORT_SECTION_SEPARATOR = "=" * 80
REPORT_SUBSECTION_SEPARATOR = "-" * 40

ENV_REPORTS_DIR = "ASR_REPORTS_DIR"
ENV_REPORTS_ENABLED = "ASR_REPORTS_ENABLED"
