asr:
  provider: whisper
  model: medium
  device: cuda  # cpu | cuda
  language: es
  compute_type: float16 # int8 | float16 | float32

pln:
  task: ner
  model: rigonsallauka/spanish_medical_ner
  aggregation_strategy: max