asr:
  provider: fast-whisper
  model: medium # base | small | medium | large-v3
  device: cuda  # cpu | cuda
  language: es
  compute_type: float16 # int8 | float16 | float32

pln_medical:
  task: ner
  model: rigonsallauka/spanish_medical_ner
  aggregation_strategy: max

pln_farmacos:
  task: token-classification
  model: PlanTL-GOB-ES/bsc-bio-ehr-es-pharmaconer
  aggregation_strategy: simple

snomed:
  enabled: true

reports:
  enabled: true