"""Constants for the coding lookup test endpoint."""

REQUEST_BODY_KEY_ENTITIES = "entities"
RESPONSE_BODY_KEY_ENTITIES = "entities"

DEFAULT_CODING_LOOKUP_ENTITY_GROUP = ""
DEFAULT_CODING_LOOKUP_SCORE = 1.0
DEFAULT_CODING_LOOKUP_START = 0
DEFAULT_CODING_LOOKUP_END = 0
DEFAULT_CODING_LOOKUP_PLN_SOURCE = ""
