/** Constants shared by the WebSocket gateway and ASR integration. */

const DEFAULT_GATEWAY_PORT = 8000;
const DEFAULT_ASR_SERVICE_URL = 'http://127.0.0.1:8001';

const PROCESSING_MODE_STREAMING = 'streaming';
const PROCESSING_MODE_BATCH = 'batch';

// const DEFAULT_PROCESSING_MODE = PROCESSING_MODE_STREAMING;
const DEFAULT_PROCESSING_MODE = PROCESSING_MODE_BATCH;
const ASR_BATCH_TIMEOUT_MS = 600_000;

const ENV_ASR_SERVICE_URL = 'ASR_SERVICE_URL';

const ASR_TRANSCRIBE_PATH = '/transcribe';
const ASR_FINALIZE_SESSION_PATH = '/finalize-session';
const ASR_GENERATE_REPORT_PATH = '/generate-report';
const ASR_GENERATE_FHIR_REPORT_PATH = '/generate-fhir-report';

const HEADER_SESSION_ID = 'X-Session-Id';
const HEADER_SEQUENCE = 'X-Sequence';
const HEADER_TIMESTAMP = 'X-Timestamp';

const CONTENT_TYPE_OCTET_STREAM = 'application/octet-stream';
const CONTENT_TYPE_JSON = 'application/json';

const TRANSCRIBE_RESPONSE_KEY_ENTITIES = 'entities';
const FHIR_REQUEST_BODY_KEY_ENTITIES = 'entities';

const WS_MESSAGE_TYPE_AUDIO_CHUNK = 'audio_chunk';
const WS_MESSAGE_TYPE_SESSION_END = 'session_end';
const WS_RESPONSE_TYPE_TRANSCRIPTION = 'transcription';
const WS_RESPONSE_TYPE_ERROR = 'error';
const WS_RESPONSE_TYPE_SESSION_END = 'session_end';
const WS_RESPONSE_TYPE_LLM_REPORT = 'llm_report';
const WS_RESPONSE_TYPE_FHIR_REPORT = 'fhir_report';

const JSON_MESSAGE_START_BYTE = 0x7b;

module.exports = {
    DEFAULT_GATEWAY_PORT,
    DEFAULT_ASR_SERVICE_URL,
    ENV_ASR_SERVICE_URL,
    ASR_TRANSCRIBE_PATH,
    ASR_FINALIZE_SESSION_PATH,
    ASR_GENERATE_REPORT_PATH,
    ASR_GENERATE_FHIR_REPORT_PATH,
    HEADER_SESSION_ID,
    HEADER_SEQUENCE,
    HEADER_TIMESTAMP,
    CONTENT_TYPE_OCTET_STREAM,
    CONTENT_TYPE_JSON,
    TRANSCRIBE_RESPONSE_KEY_ENTITIES,
    FHIR_REQUEST_BODY_KEY_ENTITIES,
    WS_MESSAGE_TYPE_AUDIO_CHUNK,
    WS_MESSAGE_TYPE_SESSION_END,
    WS_RESPONSE_TYPE_TRANSCRIPTION,
    WS_RESPONSE_TYPE_ERROR,
    WS_RESPONSE_TYPE_SESSION_END,
    WS_RESPONSE_TYPE_LLM_REPORT,
    WS_RESPONSE_TYPE_FHIR_REPORT,
    JSON_MESSAGE_START_BYTE,
    PROCESSING_MODE_STREAMING,
    PROCESSING_MODE_BATCH,
    DEFAULT_PROCESSING_MODE,
    ASR_BATCH_TIMEOUT_MS,
};
